#!/usr/bin/env bash
# Write only the non-secret MQTT routing config to a TC002 writable directory.
# This never touches /res, update.img, or any firmware partition.
set -euo pipefail

ADB_TARGET=""
LAN_HOST=""
TOPIC="ulanzi/tc002-focus/events/focus"
REMOTE_DIR="/mnt/extsd/focus-app"

alarm() { printf 'ALARM %s\n' "$*" >&2; exit 2; }

usage() {
  cat <<'USAGE'
用法: companion/configure-device.sh [选项]

  --adb-target <ip:5555>  adb 目标，例如 192.0.2.131:5555（仅示例）
  --lan-host <ip>         运行 EMQX 的电脑局域网地址
  --mqtt-topic <topic>    设备事件精确主题
  --remote-dir <path>     可写运行目录（默认 /mnt/extsd/focus-app）

这个脚本只写 device.conf，不改 /res，不刷 update.img。
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --adb-target) ADB_TARGET="${2:-}"; shift 2 ;;
    --lan-host) LAN_HOST="${2:-}"; shift 2 ;;
    --mqtt-topic) TOPIC="${2:-}"; shift 2 ;;
    --remote-dir) REMOTE_DIR="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) alarm "未知参数: $1" ;;
  esac
done

command -v adb >/dev/null 2>&1 || alarm "找不到 adb"
[ -n "$ADB_TARGET" ] || alarm "必须提供 --adb-target"
[ -n "$LAN_HOST" ] || alarm "必须提供 --lan-host"
case "$LAN_HOST" in *[!0-9.]*) alarm "--lan-host 必须是 IPv4 地址" ;; esac
case "$TOPIC" in *'#'*|*'+'*|''|*[!A-Za-z0-9_./-]*) alarm "--mqtt-topic 必须是固定 MQTT 主题" ;; esac
case "$REMOTE_DIR" in /*) ;; *) alarm "--remote-dir 必须是绝对路径" ;; esac

TEMP_FILE="$(mktemp /tmp/tc002-device-conf.XXXXXX)"
cleanup() { rm -f "$TEMP_FILE"; }
trap cleanup EXIT

printf '%s\n' \
  '# Generated by Ulanzi Focus Companion. No Lark token is stored here.' \
  "broker_host=$LAN_HOST" \
  'broker_port=1883' \
  "event_topic=$TOPIC" > "$TEMP_FILE"

adb -s "$ADB_TARGET" shell "mkdir -p '$REMOTE_DIR'"
adb -s "$ADB_TARGET" push "$TEMP_FILE" "$REMOTE_DIR/device.conf"
printf '已写入 %s/device.conf（只包含 MQTT 地址和主题）。\n' "$REMOTE_DIR"
